name: Benchmark sumi

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: rustup toolchain install nightly
      
    - name: Cache rust environment
      uses: Swatinem/rust-cache@v2

    - name: Install wrk
      run: sudo apt-get update && sudo apt-get install -y wrk

    - name: Build sumi
      run: cargo +nightly build --release

    - name: Make cards.txt from assets folder
      run: |
        find assets -name "*.webp" | sed 's|assets/||' | sed 's|\.webp||' > cards.txt
        echo "generated cards.txt"
        cat cards.txt

    - name: Start sumi and Run benchmark
      env:
        CARDS_DIR: "assets"
        PORT: 6767
        RUST_LOG: info
      run: |
        ./target/release/sumi > sumi.log 2>&1 &
        SUMI_PID=$!
        sleep 3
        wrk -t4 -c4 -d10s -s benchmark.lua http://localhost:6767
        echo -e "\n\n\n"
        wrk -t4 -c100 -d30s --timeout 10s -s benchmark.lua http://localhost:6767
        kill $SUMI_PID || true
        echo -e "\n"
        cat sumi.log
  
