name: Benchmark sumi

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: rustup toolchain install nightly

    - name: Install wrk
      run: sudo apt-get update && sudo apt-get install -y wrk

    - name: Build sumi
      run: cargo +nightly build --release

    - name: Make cards.txt from assets folder
      run: |
        find assets -name "*.webp" | sed 's|assets/||' | sed 's|\.webp||' > cards.txt
        echo "generated cards.txt"
        cat cards.txt

    - name: Start sumi and Run benchmark
      env:
        CARDS_DIR: "assets"
        PORT: 6767
        RUST_LOG: debug
      run: |
        cargo +nightly run --release > sumi.log 2>&1 &
        SUMI_PID=$!
        tail -f sumi.log &
        TAIL_PID=$!
        sleep 5
        wrk -t4 -c100 -d30s --timeout 10s -s benchmark.lua http://localhost:6767
        kill $SUMI_PID || true
        kill $TAIL_PID || true
