name: Check Unused Features

on:
  workflow_dispatch: # Allows triggering this manually

jobs:
  check-features:
    name: Find Unused Cargo Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-unused-features
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-unused-features

      - name: Workaround for cargo-unused-features
        run: sed -i 's/edition = "2024"/edition = "2021"/' Cargo.toml

      - name: Run cargo-unused-features
        run: unused-features analyze

      - name: Show Results
        run: cat report.json | jq .

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: unused-features-report
          path: report.json
